source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'sinatra-activerecord'
gem 'rake'
gem 'slack-notifier'
gem 'sqlite3'
gem 'dotenv'
gem 'redis-objects'
